---
development:
  cloud_name: playlistr
  api_key: '785365645962482'
  api_secret: MnM9qBcXm8K3aO7DOpWdQlCos6k
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: playlistr
  api_key: '785365645962482'
  api_secret: MnM9qBcXm8K3aO7DOpWdQlCos6k
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: playlistr
  api_key: '785365645962482'
  api_secret: MnM9qBcXm8K3aO7DOpWdQlCos6k
  enhance_image_tag: true
  static_image_support: false
